# Generated by Django 4.2.7 on 2025-10-10 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0013_imagenproducto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImagenProducto',
        ),
    ]
