# Generated by Django 4.2.7 on 2025-10-11 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0015_imagenproducto'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrecioCantidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_minima', models.IntegerField(help_text='Cantidad mínima para aplicar este precio')),
                ('precio', models.DecimalField(decimal_places=2, help_text='Precio por unidad para esta cantidad', max_digits=10)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios_cantidad', to='productos.producto')),
            ],
            options={
                'verbose_name': 'Precio por Cantidad',
                'verbose_name_plural': 'Precios por Cantidad',
                'ordering': ['cantidad_minima'],
                'unique_together': {('producto', 'cantidad_minima')},
            },
        ),
    ]
