# Generated by Django 4.2.7 on 2025-10-11 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0016_preciocantidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpcionProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: 200 hojas', max_length=200)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('orden', models.IntegerField(default=0)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='productos.producto')),
            ],
            options={
                'verbose_name': 'Opción de Producto',
                'verbose_name_plural': 'Opciones de Producto',
                'ordering': ['orden'],
            },
        ),
        migrations.DeleteModel(
            name='PrecioCantidad',
        ),
    ]
