# Generated by Django 4.2.7 on 2025-10-27 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0017_opcionproducto_delete_preciocantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen_url',
            field=models.URLField(blank=True, help_text='URL externa de la imagen', null=True),
        ),
    ]
