# Generated by Django 4.2.7 on 2025-10-28 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0018_producto_imagen_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='footerconfig',
            name='color_hover',
            field=models.CharField(default='#aeefff', help_text='Color hover de enlaces', max_length=7),
        ),
    ]
