# Generated by Django 4.2.7 on 2025-11-01 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0019_footerconfig_color_hover'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallepedido',
            name='personalizacion',
            field=models.TextField(blank=True, help_text='Texto de personalización del cliente'),
        ),
        migrations.AddField(
            model_name='producto',
            name='permite_personalizacion',
            field=models.BooleanField(default=False, help_text='¿Este producto permite personalización?'),
        ),
        migrations.AddField(
            model_name='producto',
            name='placeholder_personalizacion',
            field=models.CharField(blank=True, help_text='Texto de ejemplo para el campo', max_length=100),
        ),
        migrations.AddField(
            model_name='producto',
            name='texto_personalizacion',
            field=models.CharField(blank=True, help_text='Ej: ¿Quieres ponerle nombre personalizado?', max_length=200),
        ),
    ]
