# Generated by Django 4.2.7 on 2025-11-05 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0020_detallepedido_personalizacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('color', models.CharField(default='#6c757d', help_text='Color del tag en formato hex', max_length=7)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Tags',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='categoria',
            name='visible_navegacion',
            field=models.BooleanField(default=True, help_text='¿Mostrar en el menú de navegación?'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Tags asociados a esta categoría', to='productos.tag'),
        ),
        migrations.AddField(
            model_name='producto',
            name='tags_adicionales',
            field=models.ManyToManyField(blank=True, help_text='Tags adicionales para este producto', to='productos.tag'),
        ),
    ]
