# Generated by Django 4.2.7 on 2025-11-05 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0021_tag_categoria_visible_navegacion_categoria_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='categoria_madre',
            field=models.ForeignKey(blank=True, help_text='Categoría padre (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategorias', to='productos.categoria'),
        ),
    ]
