# Generated by Django 4.2.7 on 2025-11-06 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0022_categoria_categoria_madre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='categoria_madre',
        ),
    ]
