# Generated by Django 4.2.7 on 2025-11-06 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0023_remove_categoria_categoria_madre'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuPersonalizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre que aparece en el menú', max_length=100)),
                ('tipo', models.CharField(choices=[('categoria', 'Categoría'), ('grupo', 'Grupo Desplegable'), ('enlace', 'Enlace Personalizado')], default='categoria', max_length=20)),
                ('url_personalizada', models.CharField(blank=True, help_text='Solo para tipo Enlace Personalizado', max_length=200)),
                ('orden', models.IntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(blank=True, help_text='Solo para tipo Categoría', null=True, on_delete=django.db.models.deletion.CASCADE, to='productos.categoria')),
                ('padre', models.ForeignKey(blank=True, help_text='Para crear submenús', null=True, on_delete=django.db.models.deletion.CASCADE, to='productos.menupersonalizado')),
            ],
            options={
                'verbose_name': 'Menú Personalizado',
                'verbose_name_plural': 'Menú Personalizado',
                'ordering': ['orden'],
            },
        ),
    ]
