# Generated by Django 4.2.7 on 2025-11-06 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0024_menupersonalizado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='productos.categoria'),
        ),
        migrations.AlterField(
            model_name='seccioncategoria',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='productos.categoria'),
        ),
        migrations.DeleteModel(
            name='MenuPersonalizado',
        ),
    ]
