# Generated by Django 4.2.7 on 2025-11-16 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0027_alter_pedido_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(help_text='Usuario de Instagram (sin @)', max_length=100)),
                ('titulo', models.CharField(default='Síguenos en Instagram', max_length=100)),
                ('mostrar_en_home', models.BooleanField(default=True)),
                ('cantidad_posts', models.IntegerField(default=6, help_text='Cantidad de posts a mostrar')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Configuración de Instagram',
                'verbose_name_plural': 'Configuración de Instagram',
            },
        ),
    ]
