# Generated by Django 4.2.7 on 2026-05-18 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0037_variantevalor_imagen_fk'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['nombre'], 'verbose_name_plural': 'Categorías'},
        ),
        migrations.AlterModelOptions(
            name='varianteatributo',
            options={'ordering': ['orden'], 'verbose_name': 'Variante', 'verbose_name_plural': 'Variantes del producto'},
        ),
        migrations.AddField(
            model_name='seccioncategoria',
            name='banner_boton_texto',
            field=models.CharField(blank=True, default='Ver todo', help_text='Texto del botón CTA', max_length=50),
        ),
        migrations.AddField(
            model_name='seccioncategoria',
            name='banner_imagen',
            field=models.ImageField(blank=True, help_text='Imagen del banner izquierdo', max_length=500, null=True, upload_to='banners/'),
        ),
        migrations.AddField(
            model_name='seccioncategoria',
            name='banner_subtitulo',
            field=models.CharField(blank=True, default='', help_text='Subtítulo o descripción breve', max_length=200),
        ),
        migrations.AddField(
            model_name='seccioncategoria',
            name='banner_titulo',
            field=models.CharField(blank=True, default='', help_text='Título del banner (ej: Recién llegados)', max_length=100),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='tags',
            field=models.ManyToManyField(blank=True, to='productos.tag'),
        ),
        migrations.AlterField(
            model_name='descuento',
            name='categorias',
            field=models.ManyToManyField(blank=True, help_text='Categorías con descuento', to='productos.categoria'),
        ),
        migrations.AlterField(
            model_name='descuento',
            name='codigo',
            field=models.CharField(blank=True, help_text='Cupón de descuento (opcional). Si no hay código, se aplica automáticamente.', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='descuento',
            name='nombre',
            field=models.CharField(help_text='Nombre interno del descuento', max_length=100),
        ),
        migrations.AlterField(
            model_name='descuento',
            name='productos',
            field=models.ManyToManyField(blank=True, help_text='Productos con descuento (si aplica a producto específico)', to='productos.producto'),
        ),
        migrations.AlterField(
            model_name='descuento',
            name='usos_maximos',
            field=models.IntegerField(blank=True, help_text='Máximo de usos. Vacío = ilimitado', null=True),
        ),
        migrations.AlterField(
            model_name='descuento',
            name='valor',
            field=models.DecimalField(decimal_places=2, help_text='Ej: 10 para 10% o 1000 para $1000', max_digits=10),
        ),
        migrations.AlterField(
            model_name='variantevalor',
            name='precio_extra',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='variantevalor',
            name='valor',
            field=models.CharField(max_length=100),
        ),
    ]
