# Generated by Django 4.2.7 on 2026-05-18 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0038_seccioncategoria_banner_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenInterior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(max_length=500, upload_to='interior/')),
                ('orden', models.IntegerField(default=0)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes_interior', to='productos.producto')),
            ],
            options={
                'verbose_name': 'Imagen de Interior',
                'verbose_name_plural': 'Imágenes de Interior',
                'ordering': ['orden'],
            },
        ),
    ]
