# Generated by Django 4.2.7 on 2026-05-26 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0040_resena'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='condicion',
            field=models.CharField(choices=[('new', 'Nuevo'), ('refurbished', 'Reacondicionado'), ('used', 'Usado')], default='new', max_length=20),
        ),
        migrations.AddField(
            model_name='producto',
            name='google_category',
            field=models.CharField(blank=True, help_text='Categoría de Google (ej: Hogar > Decoración)', max_length=300),
        ),
        migrations.AddField(
            model_name='producto',
            name='marca',
            field=models.CharField(default='Mundo Magie', help_text='Marca del producto', max_length=100),
        ),
        migrations.AddField(
            model_name='producto',
            name='mpn',
            field=models.CharField(blank=True, help_text='Número de parte del fabricante (único por producto)', max_length=100),
        ),
        migrations.AddField(
            model_name='producto',
            name='sincronizar_google',
            field=models.BooleanField(default=True, help_text='¿Sincronizar con Google Shopping?'),
        ),
    ]
