# Generated by Django 4.2.7 on 2026-05-26 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0041_google_shopping_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='google_category',
            field=models.CharField(blank=True, choices=[('', '-- Seleccionar --'), ('Arts & Entertainment > Party & Celebration > Party Supplies', 'Artículos de Fiesta'), ('Arts & Entertainment > Party & Celebration > Party Favors', 'Sorpresas / Cotillón'), ('Arts & Entertainment > Party & Celebration > Gift Wrapping', 'Envoltorios de Regalo'), ('Arts & Entertainment > Party & Celebration > Party Decorations', 'Decoración de Fiestas'), ('Arts & Entertainment > Party & Celebration > Banners', 'Banners y Guirnaldas'), ('Arts & Entertainment > Party & Celebration > Invitations', 'Invitaciones'), ('Arts & Entertainment > Party & Celebration > Party Hats', 'Gorros de Fiesta'), ('Home & Garden > Decor', 'Decoración del Hogar'), ('Home & Garden > Decor > Candles', 'Velas Decorativas'), ('Food, Beverages & Tobacco > Food Items > Candy & Chocolate', 'Dulces y Chocolates'), ('Toys & Games', 'Juguetes'), ('Toys & Games > Puzzles', 'Puzzles'), ('Toys & Games > Stuffed Animals', 'Peluches'), ('Baby & Toddler > Baby Shower', 'Baby Shower'), ('Office Supplies > Paper Products > Stationery', 'Papelería'), ('Office Supplies > Paper Products > Gift Cards', 'Tarjetas de Regalo'), ('Apparel & Accessories > Costumes & Accessories', 'Disfraces y Accesorios'), ('Arts & Entertainment > Crafts > Craft Supplies', 'Manualidades')], help_text='Categoría de Google Shopping', max_length=300),
        ),
    ]
