# Generated by Django 4.2.7 on 2026-05-27 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0042_google_category_choices'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variantevalor',
            old_name='precio_extra',
            new_name='precio',
        ),
        migrations.AlterField(
            model_name='variantevalor',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Precio real de esta variante (ej: 15000, 18000). Si es 0, usa el precio base del producto.', max_digits=10),
        ),
    ]
