# Generated by Django 4.2.7 on 2026-07-04 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0043_rename_precio_extra_to_precio'),
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER TABLE productos_producto ADD COLUMN IF NOT EXISTS es_digital boolean NOT NULL DEFAULT false;",
            reverse_sql="ALTER TABLE productos_producto DROP COLUMN IF EXISTS es_digital;",
        ),
    ]
