# Generated by Django 4.2.7 on 2026-07-04 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0043_rename_precio_extra_to_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='es_digital',
            field=models.BooleanField(default=False, help_text='¿Es un producto digital? Se enviará por correo electrónico.'),
        ),
    ]
