# Generated by Django 4.2.7 on 2026-07-04 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0044_producto_es_digital'),
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER TABLE productos_producto ADD COLUMN IF NOT EXISTS archivo_digital varchar(100) NULL;",
            reverse_sql="ALTER TABLE productos_producto DROP COLUMN IF EXISTS archivo_digital;",
        ),
        migrations.RunSQL(
            sql="ALTER TABLE productos_producto ADD COLUMN IF NOT EXISTS es_digital boolean NOT NULL DEFAULT false;",
            reverse_sql="ALTER TABLE productos_producto DROP COLUMN IF EXISTS es_digital;",
        ),
    ]
