# Generated by Django 4.2.7 on 2026-07-04 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0045_producto_archivo_digital_producto_es_digital'),
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER TABLE productos_producto ADD COLUMN IF NOT EXISTS archivo_digital varchar(100) NULL;",
            reverse_sql="ALTER TABLE productos_producto DROP COLUMN IF EXISTS archivo_digital;",
        ),
        migrations.RunSQL(
            sql="ALTER TABLE productos_producto ADD COLUMN IF NOT EXISTS es_digital boolean NOT NULL DEFAULT false;",
            reverse_sql="ALTER TABLE productos_producto DROP COLUMN IF EXISTS es_digital;",
        ),
        migrations.CreateModel(
            name='TokenDescarga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, unique=True)),
                ('fecha_expiracion', models.DateTimeField()),
                ('usado', models.BooleanField(default=False)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.pedido')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto')),
            ],
            options={
                'verbose_name': 'Token de Descarga',
                'verbose_name_plural': 'Tokens de Descarga',
            },
        ),
    ]
