# Generated by Django 5.2.15 on 2026-07-08 23:19

from django.db import migrations, models
from django.utils.text import slugify
import unicodedata


def generar_slugs(apps, schema_editor):
    Producto = apps.get_model('productos', 'Producto')
    for p in Producto.objects.all():
        if not p.slug:
            base = slugify(unicodedata.normalize('NFKD', p.nombre))
            slug, n = base, 1
            while Producto.objects.filter(slug=slug).exclude(pk=p.pk).exists():
                slug = f'{base}-{n}'
                n += 1
            p.slug = slug
            p.save(update_fields=['slug'])


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0046_producto_archivo_digital_producto_es_digital_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, default=''),
        ),
        migrations.RunPython(generar_slugs, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='producto',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='google_category',
            field=models.CharField(blank=True, choices=[('', '-- Seleccionar --'), ('5709', 'Artículos de Fiesta'), ('96', 'Sorpresas / Cotillón'), ('5710', 'Envoltorios de Regalo'), ('5711', 'Decoración de Fiestas'), ('5712', 'Banners y Guirnaldas'), ('5713', 'Invitaciones'), ('5714', 'Gorros de Fiesta'), ('536', 'Decoración del Hogar'), ('592', 'Velas Decorativas'), ('1876', 'Dulces y Chocolates'), ('1253', 'Juguetes'), ('3867', 'Puzzles'), ('4352', 'Peluches'), ('5593', 'Baby Shower'), ('923', 'Papelería'), ('5874', 'Tarjetas de Regalo'), ('5192', 'Disfraces y Accesorios'), ('505370', 'Manualidades')], help_text='Categoría de Google Shopping', max_length=300),
        ),
    ]
