# Generated by Django 4.2.7 on 2026-07-17 22:16

from django.db import migrations, models, connection


def add_column_if_not_exists(schema_editor, model, field_name, field_sql):
    table = model
    with connection.cursor() as cursor:
        cursor.execute("""
            SELECT column_name FROM information_schema.columns
            WHERE table_name = %s AND column_name = %s
        """, [table, field_name])
        if not cursor.fetchone():
            cursor.execute(f'ALTER TABLE "{table}" ADD COLUMN {field_sql}')


def forwards(apps, schema_editor):
    cols = [
        ('productos_contacto',     'whatsapp',               "whatsapp VARCHAR(20) NOT NULL DEFAULT ''"),
        ('productos_contacto',     'whatsapp_mensaje',        "whatsapp_mensaje VARCHAR(200) NOT NULL DEFAULT 'Hola! Me interesa un producto'"),
        ('productos_detallepedido','imagen_personalizacion',  "imagen_personalizacion VARCHAR(100) NULL"),
        ('productos_producto',     'archivo_digital',         "archivo_digital VARCHAR(100) NULL"),
        ('productos_producto',     'es_digital',              "es_digital BOOLEAN NOT NULL DEFAULT FALSE"),
        ('productos_producto',     'permite_foto',            "permite_foto BOOLEAN NOT NULL DEFAULT FALSE"),
        ('productos_producto',     'placeholder_foto',        "placeholder_foto VARCHAR(200) NOT NULL DEFAULT 'Ej: foto de tu mascota, logo, diseño...'"),
        ('productos_producto',     'texto_foto',              "texto_foto VARCHAR(200) NOT NULL DEFAULT 'Sube tu foto de referencia'"),
    ]
    for table, col, sql in cols:
        add_column_if_not_exists(schema_editor, table, col, sql)


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0050_producto_permite_foto'),
    ]

    operations = [
        migrations.RunPython(forwards, migrations.RunPython.noop),
        # Estado final del modelo para que Django lo reconozca
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='contacto',
                    name='whatsapp',
                    field=models.CharField(blank=True, max_length=20, default=''),
                ),
                migrations.AddField(
                    model_name='contacto',
                    name='whatsapp_mensaje',
                    field=models.CharField(blank=True, default='Hola! Me interesa un producto', max_length=200),
                ),
                migrations.AddField(
                    model_name='detallepedido',
                    name='imagen_personalizacion',
                    field=models.ImageField(blank=True, null=True, upload_to='personalizaciones/'),
                ),
                migrations.AddField(
                    model_name='producto',
                    name='archivo_digital',
                    field=models.FileField(blank=True, null=True, upload_to='digitales/'),
                ),
                migrations.AddField(
                    model_name='producto',
                    name='es_digital',
                    field=models.BooleanField(default=False),
                ),
                migrations.AddField(
                    model_name='producto',
                    name='permite_foto',
                    field=models.BooleanField(default=False),
                ),
                migrations.AddField(
                    model_name='producto',
                    name='placeholder_foto',
                    field=models.CharField(blank=True, default='Ej: foto de tu mascota, logo, diseño...', max_length=200),
                ),
                migrations.AddField(
                    model_name='producto',
                    name='texto_foto',
                    field=models.CharField(blank=True, default='Sube tu foto de referencia', max_length=200),
                ),
            ],
            database_operations=[],
        ),
    ]
