# Generated by Django 4.2.7 on 2026-07-17 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0050_producto_permite_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='whatsapp',
            field=models.CharField(blank=True, help_text='Número con código de país, sin + ni espacios. Ej: 56912345678', max_length=20),
        ),
        migrations.AddField(
            model_name='contacto',
            name='whatsapp_mensaje',
            field=models.CharField(blank=True, default='Hola! Me interesa un producto 😊', help_text='Mensaje predeterminado al abrir WhatsApp', max_length=200),
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='imagen_personalizacion',
            field=models.ImageField(blank=True, help_text='Imagen subida por el cliente', null=True, upload_to='personalizaciones/'),
        ),
        migrations.AddField(
            model_name='producto',
            name='archivo_digital',
            field=models.FileField(blank=True, help_text='Archivo a enviar por correo al comprar (PDF, ZIP, etc.)', null=True, upload_to='digitales/'),
        ),
        migrations.AddField(
            model_name='producto',
            name='es_digital',
            field=models.BooleanField(default=False, help_text='¿Es un producto digital? Se enviará por correo electrónico.'),
        ),
        migrations.AddField(
            model_name='producto',
            name='permite_foto',
            field=models.BooleanField(default=False, help_text='¿El cliente puede subir una foto para este producto?'),
        ),
        migrations.AddField(
            model_name='producto',
            name='placeholder_foto',
            field=models.CharField(blank=True, default='Ej: foto de tu mascota, logo, diseño...', help_text='Descripción o instrucción para el cliente', max_length=200),
        ),
        migrations.AddField(
            model_name='producto',
            name='texto_foto',
            field=models.CharField(blank=True, default='Sube tu foto de referencia', help_text='Título del campo de foto', max_length=200),
        ),
    ]
