# Generated by Django 4.2.7 on 2026-07-18 03:20

from django.db import migrations, models, connection


def add_column_if_not_exists(schema_editor, model, field_name, field_sql):
    with connection.cursor() as cursor:
        cursor.execute("""
            SELECT column_name FROM information_schema.columns
            WHERE table_name = %s AND column_name = %s
        """, [model, field_name])
        if not cursor.fetchone():
            cursor.execute(f'ALTER TABLE "{model}" ADD COLUMN {field_sql}')


def forwards(apps, schema_editor):
    cols = [
        ('productos_configuracionsitio', 'moneda_simbolo',   "moneda_simbolo VARCHAR(5) NOT NULL DEFAULT '$'"),
        ('productos_configuracionsitio', 'seo_descripcion',  "seo_descripcion VARCHAR(160) NOT NULL DEFAULT ''"),
        ('productos_configuracionsitio', 'seo_titulo',       "seo_titulo VARCHAR(70) NOT NULL DEFAULT ''"),
    ]
    for table, col, sql in cols:
        add_column_if_not_exists(schema_editor, table, col, sql)


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0051_contacto_whatsapp'),
    ]

    operations = [
        migrations.RunPython(forwards, migrations.RunPython.noop),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='configuracionsitio',
                    name='moneda_simbolo',
                    field=models.CharField(blank=True, default='$', max_length=5),
                ),
                migrations.AddField(
                    model_name='configuracionsitio',
                    name='seo_descripcion',
                    field=models.CharField(blank=True, default='', max_length=160),
                ),
                migrations.AddField(
                    model_name='configuracionsitio',
                    name='seo_titulo',
                    field=models.CharField(blank=True, default='', max_length=70),
                ),
            ],
            database_operations=[],
        ),
    ]
