# Generated by Django 4.2.7 on 2026-07-18 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0051_contacto_whatsapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionsitio',
            name='moneda_simbolo',
            field=models.CharField(blank=True, default='$', help_text='Símbolo de moneda. Ej: $, CLP, USD', max_length=5),
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='seo_descripcion',
            field=models.CharField(blank=True, default='Descubre productos únicos en Mundo Magie. Artículos especiales hechos con amor para hacer de cada momento algo mágico.', help_text='Descripción para Google (máx 155 caracteres)', max_length=160),
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='seo_titulo',
            field=models.CharField(blank=True, default='Mundo Magie - Productos únicos y mágicos', help_text='Título que aparece en Google (máx 60 caracteres)', max_length=70),
        ),
    ]
