# Generated by Django 4.2.7 on 2026-07-19 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0053_fix_columnas_faltantes'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='email_cliente',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='configuracionsitio',
            name='moneda_simbolo',
            field=models.CharField(blank=True, default='$', help_text='Símbolo de moneda. Ej: $, CLP, USD', max_length=5),
        ),
        migrations.AlterField(
            model_name='configuracionsitio',
            name='seo_descripcion',
            field=models.CharField(blank=True, default='Descubre productos únicos en Mundo Magie. Artículos especiales hechos con amor para hacer de cada momento algo mágico.', help_text='Descripción para Google (máx 155 caracteres)', max_length=160),
        ),
        migrations.AlterField(
            model_name='configuracionsitio',
            name='seo_titulo',
            field=models.CharField(blank=True, default='Mundo Magie - Productos únicos y mágicos', help_text='Título que aparece en Google (máx 60 caracteres)', max_length=70),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='whatsapp',
            field=models.CharField(blank=True, help_text='Número con código de país, sin + ni espacios. Ej: 56912345678', max_length=20),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='whatsapp_mensaje',
            field=models.CharField(blank=True, default='Hola! Me interesa un producto 😊', help_text='Mensaje predeterminado al abrir WhatsApp', max_length=200),
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='imagen_personalizacion',
            field=models.ImageField(blank=True, help_text='Imagen subida por el cliente', null=True, upload_to='personalizaciones/'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='archivo_digital',
            field=models.FileField(blank=True, help_text='Archivo a enviar por correo al comprar (PDF, ZIP, etc.)', null=True, upload_to='digitales/'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='es_digital',
            field=models.BooleanField(default=False, help_text='¿Es un producto digital? Se enviará por correo electrónico.'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='permite_foto',
            field=models.BooleanField(default=False, help_text='¿El cliente puede subir una foto para este producto?'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='placeholder_foto',
            field=models.CharField(blank=True, default='Ej: foto de tu mascota, logo, diseño...', help_text='Descripción o instrucción para el cliente', max_length=200),
        ),
        migrations.AlterField(
            model_name='producto',
            name='texto_foto',
            field=models.CharField(blank=True, default='Sube tu foto de referencia', help_text='Título del campo de foto', max_length=200),
        ),
    ]
