# Generated by Django 4.2.7 on 2026-07-19 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0054_pedido_email_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionsitio',
            name='color_nav',
            field=models.CharField(default='#ffffff', help_text='Color de fondo del menú de navegación', max_length=7),
        ),
    ]
