# Generated by Django 4.2.7 on 2026-09-20 18:17

from django.db import migrations, models
import django.db.models.deletion
import productos.models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0056_tokendescarga_email_fecha_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='archivo_digital',
            field=models.FileField(blank=True, help_text='Archivo a enviar por correo al comprar (PDF, ZIP, etc.)', null=True, storage=productos.models._get_digital_storage, upload_to='digitales/'),
        ),
        migrations.CreateModel(
            name='AgendaMes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge', models.CharField(blank=True, default='', help_text='Ej: Agosto 2025', max_length=50)),
                ('subtitulo', models.CharField(blank=True, default='', help_text='Frase breve bajo el título', max_length=200)),
                ('banner_imagen', models.ImageField(blank=True, help_text='Imagen de fondo del banner (opcional)', max_length=500, null=True, upload_to='agenda_mes/')),
                ('activo', models.BooleanField(default=True)),
                ('producto', models.ForeignKey(blank=True, help_text='Producto que se destacará como agenda del mes', null=True, on_delete=django.db.models.deletion.SET_NULL, to='productos.producto')),
            ],
            options={
                'verbose_name': 'Agenda del Mes',
                'verbose_name_plural': 'Agenda del Mes',
            },
        ),
    ]
