# Generated by Django 4.2.7 on 2026-09-20 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0057_agenda_mes'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendames',
            name='color_fondo',
            field=models.CharField(default='#f9e4f0', help_text='Color sólido de fondo cuando no hay imagen. Ej: #f9e4f0', max_length=7),
        ),
    ]
