# Generated by Django 4.2.7 on 2026-09-20 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0058_agenda_mes_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendames',
            name='color_texto',
            field=models.CharField(default='#2a2a2a', help_text='Color del título, precio y textos principales', max_length=7),
        ),
        migrations.AddField(
            model_name='agendames',
            name='imagen_padding',
            field=models.IntegerField(default=24, help_text='Espacio interior de la imagen en px (0 = sin espacio, 40 = mucho espacio)'),
        ),
        migrations.AddField(
            model_name='agendames',
            name='imagen_posicion',
            field=models.CharField(choices=[('derecha', 'Imagen a la derecha'), ('izquierda', 'Imagen a la izquierda')], default='derecha', help_text='¿Dónde aparece la imagen del producto?', max_length=10),
        ),
        migrations.AddField(
            model_name='agendames',
            name='texto_btn_carrito',
            field=models.CharField(default='Agregar', help_text='Texto del botón de carrito', max_length=50),
        ),
        migrations.AddField(
            model_name='agendames',
            name='texto_btn_ver',
            field=models.CharField(default='Ver detalles', help_text='Texto del botón principal', max_length=50),
        ),
        migrations.AlterField(
            model_name='agendames',
            name='badge',
            field=models.CharField(blank=True, default='', help_text='Ej: ✦ Agosto 2025 ✦', max_length=50),
        ),
        migrations.AlterField(
            model_name='agendames',
            name='banner_imagen',
            field=models.ImageField(blank=True, help_text='Imagen de fondo del banner (opcional). Si no subes, se usa el color de fondo.', max_length=500, null=True, upload_to='agenda_mes/'),
        ),
        migrations.AlterField(
            model_name='agendames',
            name='color_fondo',
            field=models.CharField(default='#f9e4f0', help_text='Color sólido de fondo (cuando no hay imagen de banner)', max_length=7),
        ),
        migrations.AlterField(
            model_name='agendames',
            name='subtitulo',
            field=models.CharField(blank=True, default='', help_text='Frase breve bajo el título del producto', max_length=200),
        ),
    ]
