# Generated by Django 4.2.7 on 2026-09-20 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0059_agenda_mes_personalizacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenHome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.JSONField(default=list, help_text='Lista ordenada de secciones')),
            ],
            options={
                'verbose_name': 'Orden del Home',
                'verbose_name_plural': 'Orden del Home',
            },
        ),
    ]
